// import type { Metadata } from "next";
// import "@/app/globals.css";
// import CustomLayout from "./CustomLayout";
// import "swiper/css/navigation"; // If you use navigation
// import "swiper/css/pagination"; // If you use pagination

// import Providers from "@/app/Providers";
// import NextTopLoader from "nextjs-toploader";

// //

// export const metadata: Metadata = {
//   title: "MTN LIVE",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   //

//   return (
//     <Providers>
//       <CustomLayout>
//         <NextTopLoader showSpinner={false} />
//         {children}
//       </CustomLayout>
//     </Providers>
//   );
// }

import CustomLayout from "./CustomLayout";
// import Navbar from "@/app/components/Navbar";
import "@/app/globals.css";
import Providers from "@/app/Providers";
import { TranslationContextProvider } from "@/contexts/TranslationContext";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import NextTopLoader from "nextjs-toploader";

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  console.log(locale);
  console.log(messages);
  return (
    <html dir={`${locale === "ar" ? "rtl" : "ltr"}`} lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <TranslationContextProvider locale={locale as "ar" | "en"}>
            {/* <div className="mx-auto max-w-4xl h-screen"> */}
            <NextTopLoader showSpinner={false} />
            {/* <Navbar locale={locale} /> */}
            <Providers>
              <CustomLayout>{children}</CustomLayout>
            </Providers>
            {/* </div> */}
          </TranslationContextProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
