"use client";

import Providers from "@/app/Providers";
// import type { Metadata } from "next";
import "../../globals.css";

import { Poppins } from "next/font/google";

// import ProvidersAuth from "./ProvidersAuth";
// import { Provider } from "react-redux";
// import { store, persistor } from "@/app/store/store";
// import { PersistGate } from "redux-persist/integration/react";

//
const poppins = Poppins({
  subsets: ["latin"], // Adjust based on your needs
  weight: ["400", "500", "600", "700"], // Define required font weights
  variable: "--font-poppins", // Define a CSS variable for the font
});

// export const metadata: Metadata = {
//   title: "MTN LIVE",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //

  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body className="font-poppins">
        {/* <ProvidersAuth>{children}</ProvidersAuth> */}
        {/* <Provider store={store}> */}
        {/* <PersistGate loading={null} persistor={persistor}> */}
        <Providers>{children}</Providers>
        {/* </PersistGate> */}
        {/* </Provider> */}
      </body>
    </html>
  );
}
